### ISSUE TITLE
Changes for different android versions in one branch

### ISSUE THREAD

**Issue by n-elloco** [sarahgoldman/cordova-print-pdf-plugin#1]
It is proposed to combine the printing methods for different versions of Android in the master branch, because the application can be are designed for different versions of Android. For example, in my application using Ionic Framework and should be supported by devices with Android 4.3+. The file package.json is not possible to specify the install plugin from two branches.

**Comment by sarahgoldman** [comment]
I agree that this should eventually exist in one branch, I just haven't had the time to integrate the Cloud Print method back into master as a fallback. Feel free to make the changes and submit a pull request or I will try to get to this in the near future.

**Comment by sarahgoldman** [comment]
I have just combined the two android printing methods into the master branch. Will use native printing when available, and will fallback to google cloud print for 4.3 and less.

The latest version with this change has been published to npm. Let me know if you have any trouble implementing this.
