### ISSUE TITLE
CDVFile.h file not found

### ISSUE THREAD

**Issue by chandrasekaranragothaman** [sarahgoldman/cordova-print-pdf-plugin#12]
..../Plugins/cordova-plugin-print-pdf/CDVPrintPDF.m:12:9: fatal error: 'CDVFile.h' file not found
# import "CDVFile.h"

```
    ^
```

1 error generated.

I see the above error when I try to deploy an ios app with this plugin. The src folder does not have CDVFile.h. Am I missing something?

**Comment by EndersonSalas** [comment]
You also need to add this plugin "cordova-plugin-file"

**Comment by sarahgoldman** [comment]
I added cordova-plugin-file to the dependency configuration in the plugin.xml file. Sorry about that!

**Comment by matthew-dean** [comment]
Hmm.... I have the cordova-plugin-file dependency and I'm still getting this error.

**Comment by ankitRay1** [comment]
fatal error: 
      'CDVFile.h' file not found
#import "CDVFile.h"
        ^~~~~~~~~~~
1 error generated.
