### ISSUE TITLE
Print multiple items at once

### ISSUE THREAD

**Issue by ardean** [sarahgoldman/cordova-print-pdf-plugin#17]
According to the used [UIPrintInteractionController class](https://developer.apple.com/documentation/uikit/uiprintinteractioncontroller) it should be possible to print multiple items at once.

- **printingItem** takes a single print-ready object.
- **printingItems** takes an array of print-ready objects.

This would be a very nice feature for me.
Thank you for this plugin.

**Comment by sarahgoldman** [comment]
Please feel free to submit a pull request if you want to develop that feature. I am no longer actively supporting this plugin.
