### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by carryonwaywardson** [sarahgoldman/cordova-print-pdf-plugin#7]
After fixing #6, can you release a new version?

**Comment by sarahgoldman** [comment]
Version has been bumped to 4.0.1, thanks for the reminder.

**Comment by JoshuaCE** [comment]
Hello, tried your plugin with the latest cordova version 6.x, its not working with iOS build. if possible please update.
Thanks

**Comment by sarahgoldman** [comment]
I am no longer actively updating this plugin, but if you can create a fix and submit a pull request I will merge it.

**Comment by saagarbethi** [comment]
Hi, I am using your cordova-print-pdf-plugin. i have added 
gap:plugin name="com.sgoldm.plugin.printPDF"  as in my config.xml, but when i am uploading the build into phonegap, it shows error  **plugin unsupported: com.sgoldm.plugin.printpdf**. 

please help me

**Comment by JoshuaCE** [comment]
@saagarbethi  try cordova-plugin-print-pdf

**Comment by sarahgoldman** [comment]
@saagarbethi The plugin name is "cordova-plugin-print-pdf". Hope that works.
